steps:
# Grant the Cloud Run service account access to the secrets
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'secrets'
    - 'add-iam-policy-binding'
    - 'db-connection-string'
    - '--member'
    - 'serviceAccount:254227348007-compute@developer.gserviceaccount.com'
    - '--role'
    - 'roles/secretmanager.secretAccessor'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'secrets'
    - 'add-iam-policy-binding'
    - 'google-client-id'
    - '--member'
    - 'serviceAccount:254227348007-compute@developer.gserviceaccount.com'
    - '--role'
    - 'roles/secretmanager.secretAccessor'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'secrets'
    - 'add-iam-policy-binding'
    - 'google-client-secret'
    - '--member'
    - 'serviceAccount:254227348007-compute@developer.gserviceaccount.com'
    - '--role'
    - 'roles/secretmanager.secretAccessor'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'secrets'
    - 'add-iam-policy-binding'
    - 'gcs-service-account'
    - '--member'
    - 'serviceAccount:254227348007-compute@developer.gserviceaccount.com'
    - '--role'
    - 'roles/secretmanager.secretAccessor'

# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/trackmyrc/app:$COMMIT_SHA'
  - '-t'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/trackmyrc/app:latest'
  - '.'

# Push to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/trackmyrc/app:$COMMIT_SHA'

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'trackmyrc'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/trackmyrc/app:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-secrets'
    - 'DATABASE_URL=db-connection-string:latest,GOOGLE_CLIENT_ID=google-client-id:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest,GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON=gcs-service-account:latest'

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/trackmyrc/app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'